config_version: 0.4
genome_folder: /project/shefflab//deploy/btref.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: 
     - GRCh38_noalt_as
    genome_description: Human / GRCh38 no-alt analysis set
  a735e331b2a8ae5cd4e7519575c4c09426a276175c57bd79:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 3701eaccf6e8b6637a8b8384abfdc052
            seek_keys:
              fasta: a735e331b2a8ae5cd4e7519575c4c09426a276175c57bd79.fa
              fai: a735e331b2a8ae5cd4e7519575c4c09426a276175c57bd79.fa.fai
              chrom_sizes: a735e331b2a8ae5cd4e7519575c4c09426a276175c57bd79.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: 
     - GRCh38_noalt_decoy_as
    genome_description: Human / GRCh38 no-alt +decoy set
remote_url_base: http://awspds.refgenie.databio.org/refgenomes.databio.org/
genome_archive_folder: /project/shefflab//deploy/btref.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
