config_version: 0.4
genome_folder: /home/nsheff/refgenie_test/genomes
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
            asset_parents: []
            asset_children: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            seek_keys:
              bowtie2_index: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
            asset_parents: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta:default
        default_tag: default
    aliases: 
     - hg38
    genome_description: hg38 descriptipon
  baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 7ce3b03e30d6ef76af8c3ad09a141dfc
            seek_keys:
              fasta: baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c.fa
              fai: baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c.fa.fai
              chrom_sizes: baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c.chrom.sizes
            asset_parents: []
            asset_children: 
             - baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 6d7b0d35fa090a2d1d93f4e6c68dbe33
            seek_keys:
              bowtie2_index: baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c
            asset_parents: 
             - baa91c8f6e2780cfd8fd1040ff37f51c379947a2a4820d6c/fasta:default
        default_tag: default
    aliases: 
     - hg19
    genome_description: hg19 description
  fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: f197c1ac4b3e4c5dd013bd2021bb32e6
            seek_keys:
              fasta: fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7.fa
              fai: fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7.fa.fai
              chrom_sizes: fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7.chrom.sizes
            asset_parents: []
            asset_children: 
             - fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: f756f8dd195756b78e2f9dfbb9146fcf
            seek_keys:
              bowtie2_index: fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7
            asset_parents: 
             - fec6bcce9821b57f98ffc5d46ebec4f2f756c2e9db800ab7/fasta:default
        default_tag: default
    aliases: 
     - hg38_chr22
    genome_description: hg38 just chr 22.
  0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4afce2deeceae65b4c0987b9297cf441
            seek_keys:
              fasta: 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1.fa
              fai: 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1.fa.fai
              chrom_sizes: 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1.chrom.sizes
            asset_parents: []
            asset_children: 
             - 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 5263d8e0dde91c66f3044e18f4f4f31c
            seek_keys:
              bowtie2_index: 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1
            asset_parents: 
             - 0f10d83b1050c08dd53189986f60970b92a315aa7a16a6f1/fasta:default
        default_tag: default
    aliases: 
     - mm10
    genome_description: mm10 description
remote_url_base: http://awspds.refgenie.databio.org/refgenomes.databio.org/
genome_archive_folder: /home/nsheff/refgenie_test/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
